# Load packages
library(conflicted)
library(rmarkdown)
library(bookdown)
library(targets)
library(assertr)
library(ape)
library(scales)
library(tidyverse)
library(rgnparser)
library(ggtree)
library(glue)
library(Polychrome)
library(patchwork)
library(magrittr)
library(deeptime)
library(ggrepel)
library(ggokabeito)
library(ggtext)
library(janitor)

# Resolve conflicts
conflict_prefer("filter", "dplyr")
conflict_prefer("extract", "magrittr")