---
title: "*Supplementary Material 2*"
subtitle: "Fossil Calibration List"
mainfont: Roboto-Regular.ttf
fontsize: 11pt
mainfontoptions: 
  - BoldFont=Roboto-Bold.ttf
  - ItalicFont=Roboto-Italic.ttf
  - BoldItalicFont=Roboto-BoldItalic.ttf
output: 
  bookdown::pdf_document2:
    citation_package: default
    toc: no
    number_sections: no
    fig_caption: yes
    keep_tex: no
    latex_engine: xelatex
    pandoc_args: [ "--csl", "frontiers.csl"]
  bookdown::word_document2:
    pandoc_args: [ "--csl", "frontiers.csl"]
    toc: no
    number_sections: no
    reference_docx: Frontiers_Template_SI.docx
header-includes: 
  - \usepackage{float} # keep figures from floating away
  - \usepackage{booktabs} # need for kable tables
  - \usepackage{colortbl} # need for kable tables
  - \makeatletter\renewcommand*{\fps@figure}{H}\makeatother # keep figures from floating away
  - \usepackage{fancyhdr} # enable header
  - \pagestyle{fancy}  # enable header
  - \fancypagestyle{plain}{\pagestyle{fancy}} # show header on first page
  - \renewcommand{\headrulewidth}{0pt} # delete line beneath header
  - \fancyhead[RE,RO]{Supplementary Material} # add header on right side
  - \fancyhead[LO,LE]{} # suppress automatic section header on left side
  - \cfoot{\thepage} # footer
editor_options: 
  chunk_output_type: console
params:
  doc_type: manual
---

---
bibliography: 
- `r here::here("ms/si_fossils.bib")`
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = 'hide')
library(glue)
library(gluedown)
library(targets)
library(tarchetypes)
library(tidyverse)
library(assertr)
```

```{r prep-fossil-data}
# Set path to fossil data
fossils_data_path <- here::here("_targets/user/data_raw/Fossils_Ferns_mod.xlsx")

# Extract fossil categories (first row of fossil data)
fossils_categories <-
  readxl::read_excel(fossils_data_path, n_max = 1) %>%
	pivot_longer(names_to = "category", values_to = "raw_names", everything()) %>%
	mutate(
		category = str_replace_all(category, "\\.\\.\\.[0-9]+", "skip") %>%
			na_if("skip")) %>%
	fill(category) %>%
	mutate(category = str_to_title(category)) %>%
	filter(category != "Pteridophy")

# Get raw column names
fossils_raw_names <-
  readxl::read_excel(fossils_data_path, skip = 1)

# Get cleaned column names
fossils_clean_names <- fossils_raw_names %>% janitor::clean_names()

# Load fossils in wide format
fossils <-
fossils_clean_names %>%
	# Filter to only those actually used in the study
	filter(used == "X") %>%
	select(-used) %>%
	select(fossil_taxon, everything()) %>%
	# Format reference key for citing with pandoc
	mutate(
		reference = as.character(glue("@{reference}"))
	)

# Make a tibble of column namees for formatting
name_tbl <- tibble(
	raw_names = colnames(fossils_raw_names),
	var = colnames(fossils_clean_names)
) %>%
	right_join(
		tibble(var = colnames(fossils)), by = "var"
	) %>%
	mutate(var_order = 1:nrow(.))

# Convert to long format
fossils_long <- fossils %>%
	mutate(across(everything(), as.character)) %>%
	pivot_longer(names_to = "var", values_to = "value", -fossil_taxon) %>%
	left_join(name_tbl, by = "var") %>%
	mutate(
		text = as.character(glue::glue("{raw_names}: {value}"))
	) %>%
	left_join(fossils_categories, by = "raw_names") %>%
	arrange(fossil_taxon, category, var_order)

#' Print a single category of fossil data
#'
#' @param fossil_data Fossil data in long form, filtered to a single
#' fossil
#' @param cat_select Category of data to print
#'
#' @return Character vector

print_fossil_cat <- function(fossil_data, cat_select) {
	data <-
    fossil_data %>% filter(category == cat_select)
	
	c(
		md_heading(cat_select, 3),
		md_bullet(data$text),
		md_blank()
	)
}

#' Print data for a single fossil
#'
#' @param fossil_data Fossil data in long form
#' @param fossil_select Selected fossil to print
#'
#' @return Character vector
#'
#' @examples
#' print_fossil(fossils_long, "Acrostichum_intertrappeum") %>%
#' 	glue::as_glue()
print_fossil <- function(fossil_data, fossil_select) {
	# Filter data to only selected fossil
	data <-
    fossils_long %>% filter(fossil_taxon == fossil_select)
	
	# Print name of fossil as header in italics
	header <-
	fossil_select %>% 
		str_replace_all("_", " ") %>%
		md_italic() %>%
		md_heading(2)
	
	categories <- unique(data$category)
	
	body <- map(categories, ~print_fossil_cat(data, .)) %>%
		unlist()
	
	c(header, body, md_blank())
}
```

```{r print-fossils, results = "asis"}
unique(fossils_long$fossil_taxon) %>%
  map(~print_fossil(fossils_long, .)) %>%
	unlist() %>%
	glue::as_glue()
```

